### ISSUE TITLE
fizmo-ncursesw vs. fizmo-sdl2, ncursesw status line truncated

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#13]
In this test situation of 3 columns in the status line, fizmo-sdl2 seems to render the output correctly - identical to the Inform 7 IDE.  But when run with fizmo-ncursesw or fizmo-console it is heavily truncated no matter how wide the screen is.

Inform 7 source, which can be compiled to .z8 file: https://raw.githubusercontent.com/BroadcastGames/Inform7_StoryCode0/master/storyFilesPile0/StatusLineOutputTest0.ni

Also note that 'wear blindfold' seems to only remove the first status line and not correctly clear the second status line. This bug happens on the sdl2 version and all versions I tested.

**Comment by chrender** [comment]
In fizmo-ncursesw the status line cannot be re-sized in a “live” manner when the window is resized, as opposed to the regular text output, which is always reformatted as soon as window changes size. The Z-Machine however will detect the new screen size as soon as some input has been processed and the status line should appear correctly after this. fizmo-console doesn't support any upper window and therefore no status line (since the upper window requires the screen to be able to absolutely position the cursor which cannot be dont from “raw” C).

The code which is executed after entering the “wear blindfold” command runs a loop overwriting only the top line with spaces, there is no output for the second line. There may be, of course, other issues which might prevent any such exiting code to run, but at the moment it simply looks as if only one line is actually being cleared.
