### ISSUE TITLE
fizmo-sdl2 ignores --window-width arg on Ubuntu 16.10

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#16]
Hi. I tried both -ww and --window-width and it seems to ignore it. Latest source code off github on Ubuntu 16.10 x64. For example, starting z-life.z5 game: http://ifdb.tads.org/viewgame?id=6qb6z8xlrclhifoi

**Comment by chrender** [comment]
It appears both `--window-width` and `--window-height` were working as intended, however since both require pixel values, which was not evident from the description, and also didn't complain or warn if invalid values were used – there's a minimum width of 200 pixels and a minimum height of 100 – there was practically no way to way to use both parameters. I've added some warning messages which will complain if invalid values are used and which also give the minimum values. This is implemented in fizmo cmmit 4522d531ed1bb779094c4b2ce8aa22a833b42f5c.
