### ISSUE TITLE
fizmo-ncursesw reports screen to game as 0x42 when actually 256x42

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#17]
On Ubuntu 16.10. Tested on a 4K  3840x2160 display resolution. Latest source code off github compiled. If I size the terminal window to 256 or more width, Fizmo seems to overflow.  Example can be seen starting ZRacer.z5 game and it reports that the screen is too small.  Thank you.

**Comment by chrender** [comment]
I've adapted fizmo's relevant screen-size functionality to use 16-bit instead of 8-bit values. When that didn't solve the problem I took a look at zracer's code, and it seems it's trying to detect the screen width from header byte $21 instead of the word at $22 – see [section 11 of the Z-Spec](http://www.frobnitz.co.uk/zmachine/1.0/sect11.html) for details – which simply means that it will never be able to read dimensions > 255. In case of dimensions greater than 255, fizmo will from now on use the fixed value 255 for these headers, so zracer will at least work, even if it can't take advantage of the whole screen.
